worker: sftp-collect
frontend: |
             {
               "name": "connection_id",
               "helperText": "The remote connection to use.",
               "placeholder": "Enter Connection Id",
               "label": "Connection Id",
               "required": true,
               "id": "sftp.source.custom.connection_id"
              }
