frontend: {
"basic_fields": [{
"name": "connection_id",
"helperText": "The remote connection to use.",
"component": "FormInputText",
"placeholder": "Enter Connection Id",
"label": "Connection Id",
"validation": {
"onIncrementalChange": {
"ValidationTypeEnums.REQUIRED": {
"message": "Connection Id is required.",
"value": true
}
}
},
"required": true,
"id": "sftp.source.custom.connection_id",
"size": "medium"

}]
}
