worker: sftp-collect
frontend: |
           {
             "basic_fields": [
            {
               "name": "connection_id",
              "helperText": "The remote connection to use.",
              "component": ComponentEnums.FormInputText,
              "placeholder": "Enter Connection Id",
              "label": "Connection Id",
              "required": true,
              "id": "sftp.source.custom.connection_id",
              "size": CommonSizeEnums.MEDIUM
            }
          ]
}
