frontend: {
    "worker": "sftp-collect",
    "properties": [
      {
        "name": "remote-path",
        "type": "basic",
        "description": "Directory on remote server to collect files from",
        "component": {
          "type": "text",
          "validation": {
            "minLength": 3,
            "maxLength": 10
          }
        },
        "deployment-property": "sftp.supplier.path"
      },
      {
        "name": "flag-file-enabled",
        "type": "advanced",
        "description": "Enable flag file check before file collection",
        "component": {
          "type": "check",
          "defaultValue": false
        },
        "deployment-property": "flag-file-enabled"
      }
    ]
  }
